### ISSUE TITLE
SignatureValue for ECDSA is not well defined enough

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/CBOR-certificates#28]
The text just states that extra padding and additional lengths are removed....

**Comment by highlunder** [comment]
Ok! I'm not sure what would be the best place to expand the explanation further.

For someone looking at our sample certificate, they will find that the asn1-signature parses like this:

30 44
  02 20 373873EF8781B88297EF235C1FACCF62DA4E44740DC2A2E6A3C6C882A3238D9C
  02 20 3AD9353BA788683B06BB48FECA16EA71171734C675C5332B2AF1CB733810A1FC

Out of which only the raw data is kept, since the length of the signature fields are known by the algorithms. 

-->
373873EF8781B88297EF235C1FACCF62DA4E44740DC2A2E6A3C6C882A3238D9C + 3AD9353BA788683B06BB48FECA16EA71171734C675C5332B2AF1CB733810A1FC

**Comment by emanjon** [comment]
Need to describe that the r and s are encoded as 32, 48, 66 bytes each . The X.509 encoding is variable lenght. Following  (padding and extra length fields which are present in the ASN.1 encoding are omitted) in a similar way as for the serialnumber is not reversable.

**Comment by emanjon** [comment]
Fixed in last submission
